const productosStock = [
    {id: 1, 
    name: "Cordero con piel de lobo",
    grape: "Malbec",
    price: 400,
    year: 2020,
    Vineyard: "Mosquita Muerta Wines",
    image: "https://www.espaciovino.com.ar/media/default/0001/61/thumb_60952_default_big.jpeg"},
    {id:2,
    name:"Domiciano cosecha noctura",
    grape:"Cabernet Franc",
    price:1200,
    year:2019,
    Vineyard: "Domiciano",
    image:"https://www.espaciovino.com.ar/media/default/0001/61/thumb_60550_default_medium.jpeg"},
    {id:3,
    name:"El joven equilibrista",
    grape:"Malbec",
    price:750,
    year:2019,
    Vineyard:"Circus Wines",
    image:"https://cepadevinos.com/wp-content/uploads/2017/07/El_Joven_Equilibrista_Malbec_qjn2ay.jpg" },
    {id:4,
    name:"Animal - Orgánico",
    grape:"Malbec",
    price:900,
    year:2019,
    Vineyard:"Natural Vineyard",
    image:"https://cepadevinos.com/wp-content/uploads/2016/09/Animal_Malbec_Organico.jpg"},
    {id:5,
    name:"Pardillos",
    grape:"Malbec",
    price:950,
    year:2020,
    Vineyard:"Pardillos",
    image:"https://cepadevinos.com/wp-content/uploads/2017/07/Padrillos_Malbec_c0itbw.jpg"},
    {id:6,
    name:"Sapo de otro pozo",
    grape:"Malbec",
    price:900,
    year:2019,
    Vineyard:"Mosquita Muerta Wines",
    image:"https://www.espaciovino.com.ar/media/default/0001/59/thumb_58716_default_big.jpeg"},
    {id:7,
    name:"La Mala María",
    grape:"Cabernet Franc",
    price:720,
    year:2019,
    Vineyard:"María Celeste Alvaro",
    image:"http://d3ugyf2ht6aenh.cloudfront.net/stores/001/129/394/products/la-mala-maria-cabernet-franc1-b30a69d109432b7ee015870659445094-640-0.png"},
    {id:8,
    name:"El Enemigo",
    grape:"Cabernet Franc",
    price:1900,
    year:2019,
    Vineyard:"Mosquita Muerta Wines",
    image:"https://www.espaciovino.com.ar/media/default/0001/59/thumb_58716_default_big.jpeg"},
    {id:9,
    name:"Alambrado",
    grape:"Cabernet Franc",
    price:600,
    year:2019,
    Vineyard:"Mosquita Muerta Wines",
    image:"https://vinotecaligier.com/media/catalog/product/cache/1/image/1000x/9df78eab33525d08d6e5fb8d27136e95/b/e/be74060.jpg"},
    {id:10,
    name:"Las Perdices Reserva",
    grape:"Cabernet Sauvignion",
    price:1500,
    year:2019,
    Vineyard:"Las Perdices",
    image:"https://www.espaciovino.com.ar/media/default/0001/54/thumb_53737_default_medium.jpeg"},
    {id:11,
    name:"Rutini",
    grape:"Cabernet Sauvignion",
    price:1600,
    year:2019,
    Vineyard:"Rutini Wines",
    image:"https://cepadevinos.com/wp-content/uploads/2017/07/Rutini_Cabernet_Sauvignon_Malbec_aoewyd.jpg"},
    {id:12,
    name:"Trumpeter Cabernet Sauvignion",
    grape:"Cabernet Sauvignion",
    price:900,
    year:2019,
    Vineyard:"Rutini Wines",
    image:"https://cepadevinos.com/wp-content/uploads/2017/07/Trumpeter_Cabernet_Sauvignon_ns62ut.jpg"}             
];

export default productosStock;